### PR TITLE
Added my md file

### PR DESCRIPTION
**Pull request by lakshyasoni**

### CODE REVIEW

**Comment by amandewatnitrr** [comment]
I guess you haven't added screenshot of your profile in imgs folder oitherwise it must have shown 2 changes.

**Comment by lakshyasoni** [comment]
It has been done and also it is showing 2 files has been changed please cross check it once!

**Comment by amandewatnitrr** [comment]
okhhh
please open the PR again and I will merge

**Comment by lakshyasoni** [comment]
Cool 🙌😊

**Pull request merged**
